package Bio::Chado::Schema::Phenotype;


1;

__END__
=pod

=encoding utf-8

=head1 NAME

Bio::Chado::Schema::Phenotype

=head1 NAME

Bio::Chado::Schema::Phenotype - Entity-attribute-value phenotypic character descriptions

=head1 CHADO MODULE

Classes in this namespace correspond to tables and views in the
Chado Phenotype module.

=head1 CLASSES

These classes are part of the L<Bio::Chado::Schema> distribution.

Below is a list of classes in this module of Chado.  Each of the
classes below corresponds to a single Chado table or view.

L<Bio::Chado::Schema::Phenotype::FeaturePhenotype>

L<Bio::Chado::Schema::Phenotype::Phenotype>

L<Bio::Chado::Schema::Phenotype::PhenotypeCvterm>

=head1 AUTHOR

Robert Buels <rbuels@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2009 by Robert Buels.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut

